version: "3.9"

services:
  roman-numeral-converter:
    image: converter/roman-numeral-converter
    hostname: roman-numeral-converter
    build:
      context: ../
      dockerfile: docker/roman-numeral-converter-app/Dockerfile
    environment:
      - "HOST_IP=logstash"
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - elasticsearch
      - logstash
      - apm-server

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    hostname: elasticsearch
    ports:
      - 9200:9200
    environment:
      - "discovery.type=single-node"
      - "network.host=0.0.0.0"
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data:rw              # Persistence data
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:9200/

  logstash:
    image: docker.elastic.co/logstash/logstash:7.2.0
    hostname: logstash
    ports:
      - 25826:25826
      - 5044:5044
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro                # Pipeline configuration
    restart: on-failure
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    hostname: kibana
    ports:
      - 5601:5601
    restart: on-failure
    depends_on:
      - elasticsearch
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5601/

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.2.0
    hostname: apm-server
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
    cap_add: [ "CHOWN", "DAC_OVERRIDE", "SETGID", "SETUID" ]
    cap_drop: [ "ALL" ]
    ports:
      - 8200:8200
    command: >
      apm-server -e
        -E apm-server.rum.enabled=true
        -E setup.kibana.host=kibana:5601
        -E setup.template.settings.index.number_of_replicas=0
        -E apm-server.kibana.enabled=true
        -E apm-server.kibana.host=kibana:5601
        -E output.elasticsearch.hosts=["elasticsearch:9200"]
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8200/
