version: "3.9"

services:
  roman-numeral-converter:
    image: converter/roman-numeral-converter
    build:
      context: ../
      dockerfile: docker/roman-numeral-converter-app/Dockerfile
    environment:
      - "HOST_IP=logstash"
    ports:
      - 8080:8080
    restart: on-failure

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    ports:
      - 9200:9200
    environment:
      - "discovery.type=single-node"
      - "network.host=0.0.0.0"
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data:rw              # Persistence data

  logstash:
    image: docker.elastic.co/logstash/logstash:7.2.0
    ports:
      - 25826:25826
      - 5044:5044
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro                # Pipeline configuration
    restart: on-failure
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    ports:
      - 5601:5601
    restart: on-failure
    depends_on:
      - elasticsearch